id: P009585
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25682
  title: ཏུན་ཧོང་གཏེར་ཡིག་ལས་བྱུང་བའི་སྤྱི་ཚོགས་དཔལ་འབྱོར་སྐོར་གྱི་ཡིག་ཚགས་དང་འཕྲོས་དོན་ལ་དཔྱད་པ།
  author: ''
  volumes: {}
