id: P009585
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25682
  title: ཏུན་ཧོང་གཏེར་ཡིག་ལས་བྱུང་བའི་སྤྱི་ཚོགས་དཔལ་འབྱོར་སྐོར་གྱི་ཡིག་ཚགས་དང་འཕྲོས་དོན་ལ་དཔྱད་པ།
  author: ''
  volumes:
    290321fbfb264107a443ba9f4385b435:
      image_group_id: I1KG25684
      title: ''
      volume_number: 1
      total_pages: 579
      base_file: v001.txt
