id: IA4074219
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:32:34+00:00'
last_modified: '2022-06-08T12:04:19.271588+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25682
  title: ཏུན་ཧོང་གཏེར་ཡིག་ལས་བྱུང་བའི་སྤྱི་ཚོགས་དཔལ་འབྱོར་སྐོར་གྱི་ཡིག་ཚགས་དང་འཕྲོས་དོན་ལ་དཔྱད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    1B9F:
      image_group_id: I1KG25684
      title: ''
      total_pages: 579
      order: 1
      base_file: 1B9F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
